ssh_authorized_keys:
- github:tinohager

write_files:
- path: /var/lib/connman/default.config
  content: |-
    [service_eth0]
    Type=ethernet
    IPv4=10.14.20.181/255.255.0.0/10.14.0.254
    IPv6=off
    Nameservers=10.14.0.254
    SearchDomains=mynetwork.local
    Domain=mynetwork.local

hostname: k3s-node02

k3os:
  data_sources:
  - cdrom
  modules:
  - kvm
  - nvme
  sysctl:
    kernel.printk: "4 4 1 7"
    kernel.kptr_restrict: "1"
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  password: S6MVAcfUKuOzNKt0343dsfs
  server_url: https://k3s-node01:6443
  token: OzN34OzN3eOzN
  k3s_args:
  - agent